### ISSUE TITLE
Spotkanie - 17.12 g. 15.00

### ISSUE THREAD

**Issue by PatrykZaniewski** [JedzenieBohater/Food-Hero#54]
Panie Doktorze, nie dostaliśmy od Pana maila, ale dla pewności jeszcze spytam. Czy nasze jutrzejsze spotkanie jest cały czas aktualne?

**Comment by szmurlor** [comment]
Tak.

**Comment by szmurlor** [comment]
Tak

**Comment by szmurlor** [comment]
Moi drodzy dzisiaj niestety jednak nie dojade... awaria samochodu. Musze jeszcze do mechanika pojechac... odezwe sie i poprosze tylko o jakis krotki raport prac. Napisze wiecej po poludniu. Zalatwimy to spotkanie zdalnie...

**Comment by PatrykZaniewski** [comment]
A jak Pan widzi to żeby spotkać się jutro o 11? Części wykładowej GUI nie ma, a spotkanie face-to-face byłoby lepsze.

**Comment by szmurlor** [comment]
Bardzo dobry pomysł!!! Sala SK 103 jest idealna. Jesteśmy umówieni - jak i tak będę w sali do waszej dyspozycji.
